"""W4 — emit the English JSS3+SS3 question bank seed.

Source-of-truth for the items is the `_ITEMS` table below. Running this
script writes the verbose JSON artifact that ships with the repo. The bank
loader (`load_english_v1_bank`) only ever reads the JSON; this script is the
one place where a content editor extends the seed.

Schema: src.learning.models.DiagnosticItem. Every row is automatically wrapped
with the standard pending-review provenance block. Review status stays
`pending_two_reviewer_signoff` until two reviewers sign off in the wiki.

Usage:
    python backend/scripts/build_english_seed_bank.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from src.learning.misconceptions import TAXONOMY_VERSION  # noqa: E402
from src.learning.models import DiagnosticItem  # noqa: E402


# (year, skill_id, topic, subtopic, prompt, correct, codes, difficulty)
Row = Tuple[str, str, str, str, str, str, Tuple[str, ...], float]


# ---------------------------------------------------------------------------
# JSS3 — 100 items
# ---------------------------------------------------------------------------

_JSS3: Sequence[Row] = (
    # ---- vocabulary / synonyms (1-20) ----
    ("JSS3", "jss3.english.vocab.synonyms", "Vocabulary", "Synonyms",
     "Choose the word closest in meaning to 'reluctant'.", "unwilling",
     ("language_comprehension",), -1.5),
    ("JSS3", "jss3.english.vocab.synonyms", "Vocabulary", "Synonyms",
     "Choose the word closest in meaning to 'rapid'.", "fast",
     ("language_comprehension",), -2.0),
    ("JSS3", "jss3.english.vocab.synonyms", "Vocabulary", "Synonyms",
     "Choose the word closest in meaning to 'tidy'.", "neat",
     ("language_comprehension",), -2.2),
    ("JSS3", "jss3.english.vocab.synonyms", "Vocabulary", "Synonyms",
     "Choose the word closest in meaning to 'commence'.", "begin",
     ("language_comprehension",), -1.2),
    ("JSS3", "jss3.english.vocab.synonyms", "Vocabulary", "Synonyms",
     "Choose the word closest in meaning to 'huge'.", "enormous",
     ("language_comprehension",), -2.0),
    ("JSS3", "jss3.english.vocab.antonyms", "Vocabulary", "Antonyms",
     "Choose the opposite of 'expand'.", "shrink",
     ("language_comprehension",), -1.5),
    ("JSS3", "jss3.english.vocab.antonyms", "Vocabulary", "Antonyms",
     "Choose the opposite of 'permit'.", "forbid",
     ("language_comprehension",), -1.2),
    ("JSS3", "jss3.english.vocab.antonyms", "Vocabulary", "Antonyms",
     "Choose the opposite of 'ancient'.", "modern",
     ("language_comprehension",), -1.8),
    ("JSS3", "jss3.english.vocab.antonyms", "Vocabulary", "Antonyms",
     "Choose the opposite of 'humble'.", "proud",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.vocab.antonyms", "Vocabulary", "Antonyms",
     "Choose the opposite of 'temporary'.", "permanent",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.vocab.word_meaning", "Vocabulary", "Word in context",
     "What does 'punctual' mean in: 'Ada is always punctual for class'?", "on time",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.vocab.word_meaning", "Vocabulary", "Word in context",
     "What does 'generous' mean in: 'Mr Bello is a generous neighbour'?", "willing to give",
     ("language_comprehension",), -1.2),
    ("JSS3", "jss3.english.vocab.word_meaning", "Vocabulary", "Word in context",
     "What does 'fragile' mean in: 'Handle the fragile parcel carefully'?", "easily broken",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.vocab.word_meaning", "Vocabulary", "Word in context",
     "What does 'cautious' mean in: 'Drivers should be cautious in the rain'?", "careful",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.vocab.word_meaning", "Vocabulary", "Word in context",
     "What does 'reluctant' mean in: 'He was reluctant to apologise'?", "unwilling",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.vocab.collocations", "Vocabulary", "Collocations",
     "Complete the phrase: 'make a ___ decision.'", "wise",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.vocab.collocations", "Vocabulary", "Collocations",
     "Complete the phrase: 'take a ___.' (a short rest)", "break",
     ("language_comprehension",), -1.5),
    ("JSS3", "jss3.english.vocab.collocations", "Vocabulary", "Collocations",
     "Complete the phrase: 'pay close ___ to the teacher.'", "attention",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.vocab.collocations", "Vocabulary", "Collocations",
     "Complete the phrase: 'do your ___.' (the school work assigned)", "homework",
     ("language_comprehension",), -2.0),
    ("JSS3", "jss3.english.vocab.collocations", "Vocabulary", "Collocations",
     "Complete the phrase: 'catch the ___.' (mode of public transport)", "bus",
     ("language_comprehension",), -2.0),

    # ---- grammar: tense (21-35) ----
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Past simple",
     "Change to past simple: 'She writes a letter to her grandmother.'",
     "She wrote a letter to her grandmother.",
     ("answer_form", "language_comprehension"), -0.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Past simple",
     "Change to past simple: 'They eat lunch at noon.'",
     "They ate lunch at noon.",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Past simple",
     "Change to past simple: 'I go to the market on Saturdays.'",
     "I went to the market on Saturday.",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Past continuous",
     "Rewrite in past continuous: 'He plays football.'",
     "He was playing football.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Present perfect",
     "Rewrite in present perfect: 'I finish my homework.'",
     "I have finished my homework.",
     ("answer_form",), 0.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Future",
     "Rewrite using 'will': 'The shop opens at eight.'",
     "The shop will open at eight.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Tense agreement",
     "Choose the correct verb: 'Yesterday we (go/went) to the cinema.'", "went",
     ("answer_form",), -1.0),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Tense agreement",
     "Choose the correct verb: 'She (has/have) two younger sisters.'", "has",
     ("answer_form",), -1.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Tense agreement",
     "Choose the correct verb: 'The boys (was/were) playing in the rain.'", "were",
     ("answer_form",), -1.0),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Tense agreement",
     "Choose the correct verb: 'Neither the captain nor the players (is/are) here.'", "are",
     ("answer_form",), 1.0),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Irregular verbs",
     "Give the past tense of 'bring'.", "brought",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Irregular verbs",
     "Give the past tense of 'catch'.", "caught",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Irregular verbs",
     "Give the past tense of 'teach'.", "taught",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Irregular verbs",
     "Give the past participle of 'write'.", "written",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.grammar.tense", "Grammar", "Irregular verbs",
     "Give the past participle of 'speak'.", "spoken",
     ("answer_form",), 0.0),

    # ---- grammar: parts of speech (36-50) ----
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Pronouns",
     "Choose the correct pronoun: 'Adaeze and (I/me) went to school together.'", "I",
     ("answer_form", "language_comprehension"), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Pronouns",
     "Choose the correct pronoun: 'The teacher gave the books to (we/us).'", "us",
     ("answer_form",), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Pronouns",
     "Replace the noun with a pronoun: 'Tunde rides Tunde's bicycle.'",
     "Tunde rides his bicycle.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Prepositions",
     "Choose the correct preposition: 'The cat sat ___ the mat.'", "on",
     ("language_comprehension",), -2.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Prepositions",
     "Choose the correct preposition: 'I am proud ___ you.'", "of",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Prepositions",
     "Choose the correct preposition: 'She is good ___ mathematics.'", "at",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Prepositions",
     "Choose the correct preposition: 'He arrived ___ the airport at noon.'", "at",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Articles",
     "Insert the correct article: 'I saw ___ owl in the garden.'", "an",
     ("language_comprehension",), -1.5),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Articles",
     "Insert the correct article: 'She is ___ honest girl.'", "an",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Articles",
     "Insert the correct article (a/an/the): 'Please pass me ___ salt.'", "the",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Conjunctions",
     "Combine with 'because': 'I stayed at home. It was raining.'",
     "I stayed at home because it was raining.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Conjunctions",
     "Combine with 'although': 'He was tired. He kept working.'",
     "Although he was tired, he kept working.",
     ("answer_form",), 0.5),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Adjectives",
     "Give the comparative form of 'good'.", "better",
     ("answer_form",), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Adjectives",
     "Give the superlative form of 'bad'.", "worst",
     ("answer_form",), -1.0),
    ("JSS3", "jss3.english.grammar.parts", "Grammar", "Adverbs",
     "Form an adverb from 'careful'.", "carefully",
     ("answer_form",), -1.5),

    # ---- comprehension (51-65) ----
    ("JSS3", "jss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'Bola left home at 6 a.m. and arrived at school at 7 a.m.' How long was Bola's journey?",
     "one hour",
     ("misread_question", "language_comprehension"), -0.5),
    ("JSS3", "jss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'The market opens at 9 and closes at 5.' How many hours is the market open?",
     "eight hours",
     ("misread_question", "language_comprehension"), 0.0),
    ("JSS3", "jss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'Kemi closed her umbrella as she stepped indoors.' What was the weather like outside?",
     "it was raining",
     ("language_comprehension",), 0.0),
    ("JSS3", "jss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'Tunde grinned when he saw his exam paper.' How did Tunde feel about his results?",
     "happy",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.comprehension.main_idea", "Comprehension", "Main idea",
     "What is the main idea: 'Reading every day improves your vocabulary, your spelling, and your ability to express ideas clearly.'",
     "Reading every day improves your English.",
     ("misread_question", "language_comprehension"), 0.5),
    ("JSS3", "jss3.english.comprehension.main_idea", "Comprehension", "Main idea",
     "What is the main idea: 'Exercise keeps the heart strong, helps you sleep better, and lifts your mood.'",
     "Exercise has several health benefits.",
     ("misread_question", "language_comprehension"), 0.5),
    ("JSS3", "jss3.english.comprehension.vocab_in_context", "Comprehension", "Vocabulary in context",
     "In 'The road was deserted at midnight', what does 'deserted' mean?", "empty",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.comprehension.vocab_in_context", "Comprehension", "Vocabulary in context",
     "In 'The mango is ripe and sweet', what does 'ripe' mean?", "ready to eat",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'There were forty-five learners in JSS3A and thirty in JSS3B.' How many learners are there altogether in JSS3?",
     "seventy-five",
     ("computation_slip", "misread_question"), -0.5),
    ("JSS3", "jss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'The library opens Monday to Friday only.' On how many days is the library open?",
     "five",
     ("misread_question",), -1.0),
    ("JSS3", "jss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'Mama wiped her hands on her apron and lifted the lid of the pot.' Where is Mama most likely to be?",
     "in the kitchen",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'Chinedu zipped up his bag and ran for the gate.' What is Chinedu about to do?",
     "leave",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.comprehension.main_idea", "Comprehension", "Title",
     "Best title for: 'The classroom was filled with new desks, fresh paint, and a working ceiling fan.'",
     "A Renovated Classroom",
     ("language_comprehension", "misread_question"), 0.5),
    ("JSS3", "jss3.english.comprehension.main_idea", "Comprehension", "Title",
     "Best title for: 'Many learners now use mobile phones to read past questions and revise on the bus.'",
     "Mobile Phones Help Revision",
     ("language_comprehension", "misread_question"), 0.5),
    ("JSS3", "jss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'Ada read three chapters on Monday and two on Tuesday.' How many chapters did Ada read in total?",
     "five",
     ("computation_slip",), -1.0),

    # ---- punctuation (66-78) ----
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "End punctuation",
     "Punctuate: 'are you coming with us'", "Are you coming with us?",
     ("answer_form",), -1.0),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "End punctuation",
     "Punctuate: 'what a beautiful day'", "What a beautiful day!",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Comma",
     "Add commas: 'I bought yam beans rice and oil.'",
     "I bought yam, beans, rice and oil.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Apostrophe",
     "Add an apostrophe: 'Folakes book is on the table.'",
     "Folake's book is on the table.",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Apostrophe",
     "Add an apostrophe: 'The childrens uniforms are new.'",
     "The children's uniforms are new.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Quotation marks",
     "Add quotation marks: 'Let us go home, said Bisi.'",
     "\"Let us go home,\" said Bisi.",
     ("answer_form",), 0.5),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Capitalisation",
     "Capitalise correctly: 'we visited lagos last december.'",
     "We visited Lagos last December.",
     ("answer_form",), -1.0),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Capitalisation",
     "Capitalise correctly: 'mr. okeke teaches english at falomo secondary school.'",
     "Mr. Okeke teaches English at Falomo Secondary School.",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Comma",
     "Add commas: 'After breakfast we read the newspaper.'",
     "After breakfast, we read the newspaper.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Comma",
     "Add a comma: 'When the bell rang the children stood up.'",
     "When the bell rang, the children stood up.",
     ("answer_form",), 0.0),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Apostrophe (contraction)",
     "Rewrite using an apostrophe: 'do not run in the corridor.'",
     "Don't run in the corridor.",
     ("answer_form",), -0.5),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Colons",
     "Punctuate: 'Bring the following items pen pencil ruler and eraser.'",
     "Bring the following items: pen, pencil, ruler and eraser.",
     ("answer_form",), 0.5),
    ("JSS3", "jss3.english.punctuation.basic", "Punctuation", "Capitalisation",
     "Capitalise correctly: 'easter falls on a sunday in april this year.'",
     "Easter falls on a Sunday in April this year.",
     ("answer_form",), -0.5),

    # ---- spelling (79-91) ----
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'recieve'.", "receive",
     ("transcription", "careless"), -0.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'occurence'.", "occurrence",
     ("transcription", "careless"), 0.0),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'seperate'.", "separate",
     ("transcription", "careless"), -0.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'definately'.", "definitely",
     ("transcription", "careless"), -0.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'embarass'.", "embarrass",
     ("transcription", "careless"), 0.0),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'goverment'.", "government",
     ("transcription", "careless"), -0.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'beleive'.", "believe",
     ("transcription",), -0.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'tommorow'.", "tomorrow",
     ("transcription",), -0.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Commonly misspelled",
     "Spell correctly: 'wether' (meaning rain or sun).", "weather",
     ("transcription", "language_comprehension"), 0.0),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Homophone",
     "Which word fits: 'I went ___ the market.' (their/there)", "there",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Homophone",
     "Which word fits: 'I ate ___ piece of cake.' (peace/piece — already given)", "a",
     ("language_comprehension",), -1.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Homophone",
     "Which word fits: 'The shop is over ___.' (their/there/they're)", "there",
     ("language_comprehension",), -0.5),
    ("JSS3", "jss3.english.spelling.common", "Spelling", "Homophone",
     "Which word fits: 'I cannot find ___ keys.' (you're/your)", "your",
     ("language_comprehension",), -1.0),

    # ---- sentence transformation / figurative (92-100) ----
    ("JSS3", "jss3.english.sentence.transformation", "Sentence", "Active/passive",
     "Change to passive: 'The cat caught the mouse.'",
     "The mouse was caught by the cat.",
     ("answer_form",), 0.5),
    ("JSS3", "jss3.english.sentence.transformation", "Sentence", "Active/passive",
     "Change to active: 'The cake was eaten by the children.'",
     "The children ate the cake.",
     ("answer_form",), 0.5),
    ("JSS3", "jss3.english.sentence.transformation", "Sentence", "Direct/indirect",
     "Rewrite in reported speech: 'Tola said, \"I am tired.\"'",
     "Tola said that she was tired.",
     ("answer_form",), 1.0),
    ("JSS3", "jss3.english.sentence.transformation", "Sentence", "Direct/indirect",
     "Rewrite in reported speech: 'The teacher said, \"Open your books.\"'",
     "The teacher told us to open our books.",
     ("answer_form",), 1.0),
    ("JSS3", "jss3.english.figurative.basic", "Figurative", "Simile",
     "Complete the simile: 'as brave as a ___.'", "lion",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.figurative.basic", "Figurative", "Simile",
     "Complete the simile: 'as busy as a ___.'", "bee",
     ("language_comprehension",), -1.0),
    ("JSS3", "jss3.english.figurative.basic", "Figurative", "Metaphor",
     "Identify the metaphor in: 'Time is money.' What is being compared?",
     "time and money",
     ("language_comprehension",), 0.5),
    ("JSS3", "jss3.english.figurative.basic", "Figurative", "Idiom",
     "What does 'spill the beans' mean?", "reveal a secret",
     ("language_comprehension",), 0.0),
    ("JSS3", "jss3.english.figurative.basic", "Figurative", "Idiom",
     "What does 'a piece of cake' mean?", "very easy",
     ("language_comprehension",), -0.5),
)


# ---------------------------------------------------------------------------
# SS3 — 100 items (higher difficulty, denser comprehension, literary)
# ---------------------------------------------------------------------------

_SS3: Sequence[Row] = (
    # ---- vocabulary / lexis (1-20) ----
    ("SS3", "ss3.english.lexis.synonyms", "Lexis", "Synonyms",
     "Choose the word closest in meaning to 'meticulous'.", "thorough",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.synonyms", "Lexis", "Synonyms",
     "Choose the word closest in meaning to 'ambiguous'.", "unclear",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.synonyms", "Lexis", "Synonyms",
     "Choose the word closest in meaning to 'tenacious'.", "determined",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.lexis.synonyms", "Lexis", "Synonyms",
     "Choose the word closest in meaning to 'ostentatious'.", "showy",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.lexis.synonyms", "Lexis", "Synonyms",
     "Choose the word closest in meaning to 'frugal'.", "thrifty",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.lexis.antonyms", "Lexis", "Antonyms",
     "Choose the opposite of 'benevolent'.", "malicious",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.lexis.antonyms", "Lexis", "Antonyms",
     "Choose the opposite of 'verbose'.", "concise",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.lexis.antonyms", "Lexis", "Antonyms",
     "Choose the opposite of 'transparent' (figurative).", "opaque",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.lexis.antonyms", "Lexis", "Antonyms",
     "Choose the opposite of 'optimistic'.", "pessimistic",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.antonyms", "Lexis", "Antonyms",
     "Choose the opposite of 'genuine'.", "fake",
     ("language_comprehension",), 0.0),
    ("SS3", "ss3.english.lexis.word_meaning", "Lexis", "Word in context",
     "What does 'eloquent' mean in: 'The candidate gave an eloquent speech'?", "fluent and persuasive",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.word_meaning", "Lexis", "Word in context",
     "What does 'inevitable' mean in: 'A clash of opinions was inevitable'?", "unavoidable",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.word_meaning", "Lexis", "Word in context",
     "What does 'mitigate' mean in: 'The government tried to mitigate flooding'?", "reduce",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.lexis.word_meaning", "Lexis", "Word in context",
     "What does 'pragmatic' mean in: 'The minister took a pragmatic approach'?", "practical",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.lexis.word_meaning", "Lexis", "Word in context",
     "What does 'plausible' mean in: 'Her excuse sounded plausible'?", "believable",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.collocations", "Lexis", "Collocations",
     "Complete: 'draw a firm ___ between right and wrong.'", "distinction",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.lexis.collocations", "Lexis", "Collocations",
     "Complete: 'meet a tight ___.'", "deadline",
     ("language_comprehension",), 0.0),
    ("SS3", "ss3.english.lexis.collocations", "Lexis", "Collocations",
     "Complete: 'pose a serious ___ to public health.'", "threat",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.collocations", "Lexis", "Collocations",
     "Complete: 'reach an unanimous ___.'", "decision",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.lexis.collocations", "Lexis", "Collocations",
     "Complete: 'a ___ of opportunity.'", "window",
     ("language_comprehension",), 1.0),

    # ---- grammar: advanced tense/aspect (21-35) ----
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Past perfect",
     "Rewrite in past perfect: 'I finish my work before the bell.'",
     "I had finished my work before the bell.",
     ("answer_form",), 0.5),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Future perfect",
     "Rewrite in future perfect: 'By next year, she completes her degree.'",
     "By next year, she will have completed her degree.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Conditional",
     "Complete the second conditional: 'If I ___ rich, I would build a school.'", "were",
     ("answer_form", "language_comprehension"), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Conditional",
     "Complete the third conditional: 'If she ___ studied harder, she would have passed.'", "had",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Subjunctive",
     "Choose: 'It is essential that he (be/is) present at the meeting.'", "be",
     ("answer_form", "language_comprehension"), 1.5),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Aspect",
     "Rewrite in the perfect continuous: 'I work here for five years.'",
     "I have been working here for five years.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Concord",
     "Choose the correct verb: 'The committee (has/have) reached its decision.'", "has",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Concord",
     "Choose: 'Each of the boys (was/were) given a prize.'", "was",
     ("answer_form",), 0.5),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Concord",
     "Choose: 'Either Tola or her sisters (is/are) coming.'", "are",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Modals",
     "Choose the more polite form: 'You (must/might) want to revise this.'", "might",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Modals",
     "Rewrite using 'should': 'It is advisable to read the question twice.'",
     "You should read the question twice.",
     ("answer_form",), 0.5),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Passive",
     "Change to passive: 'The chairman opened the conference.'",
     "The conference was opened by the chairman.",
     ("answer_form",), 0.5),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Passive",
     "Change to passive: 'They will announce the results tomorrow.'",
     "The results will be announced tomorrow.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Reported speech",
     "Convert to reported speech: 'Ada said, \"I am leaving now.\"'",
     "Ada said that she was leaving then.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.tense", "Grammar", "Reported speech",
     "Convert to reported speech: 'He asked, \"Have you eaten?\"'",
     "He asked whether I had eaten.",
     ("answer_form",), 1.5),

    # ---- grammar: parts of speech / structure (36-50) ----
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Relative clause",
     "Combine: 'The man is my uncle. He gave us the books.'",
     "The man who gave us the books is my uncle.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Relative clause",
     "Combine: 'This is the school. I learned to read there.'",
     "This is the school where I learned to read.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Participles",
     "Reduce the clause: 'Because he was tired, he slept early.'",
     "Being tired, he slept early.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Participles",
     "Reduce: 'The man who was sitting by the door waved at us.'",
     "The man sitting by the door waved at us.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Gerunds and infinitives",
     "Choose: 'I enjoy (read/reading) novels.'", "reading",
     ("answer_form",), 0.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Gerunds and infinitives",
     "Choose: 'She refused (to leave/leaving) the room.'", "to leave",
     ("answer_form",), 0.5),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Determiners",
     "Choose: '(Few/A few) students passed; we should celebrate them.'", "A few",
     ("language_comprehension", "answer_form"), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Determiners",
     "Choose: 'There is (little/a little) sugar left; we cannot make tea.'", "little",
     ("language_comprehension", "answer_form"), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Prepositions",
     "Choose the correct preposition: 'Different ___ Yoruba, Igbo uses tones.'", "from",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Prepositions",
     "Choose: 'Congratulations ___ your promotion.'", "on",
     ("language_comprehension",), 0.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Conjunctions",
     "Combine using 'whereas': 'Tola is calm. Tunde is hot-tempered.'",
     "Tola is calm whereas Tunde is hot-tempered.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Conjunctions",
     "Combine using 'in order that': 'I study hard. I can pass JAMB.'",
     "I study hard in order that I can pass JAMB.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Parallelism",
     "Rewrite for parallelism: 'She likes singing, dancing and to swim.'",
     "She likes singing, dancing and swimming.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Parallelism",
     "Rewrite for parallelism: 'The job requires patience, skill and being honest.'",
     "The job requires patience, skill and honesty.",
     ("answer_form",), 1.5),
    ("SS3", "ss3.english.grammar.parts", "Grammar", "Dangling modifier",
     "Fix the dangling modifier: 'Walking to school, the rain started.'",
     "While I was walking to school, the rain started.",
     ("answer_form",), 1.5),

    # ---- comprehension (51-70) ----
    ("SS3", "ss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'The flight to Abuja departs at 07:40 and lands at 09:05.' How long is the flight?",
     "one hour and twenty-five minutes",
     ("computation_slip", "misread_question"), 0.5),
    ("SS3", "ss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'The library opens at 8 a.m. and closes at 6 p.m. on weekdays.' For how many hours is the library open on a weekday?",
     "ten",
     ("computation_slip",), -0.5),
    ("SS3", "ss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'She forced a smile and looked away.' What is most likely true about the speaker?",
     "she was not happy",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'He clutched the trophy as though it might vanish.' What does this suggest about the character?",
     "he was overjoyed and disbelieving",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.comprehension.main_idea", "Comprehension", "Main idea",
     "Identify the main idea: 'Vaccines reduce the spread of disease, ease pressure on hospitals, and save lives.'",
     "Vaccines have several public-health benefits.",
     ("misread_question", "language_comprehension"), 1.0),
    ("SS3", "ss3.english.comprehension.main_idea", "Comprehension", "Main idea",
     "Identify the main idea: 'Reading widely sharpens reasoning, deepens empathy, and improves writing.'",
     "Reading widely has many benefits.",
     ("misread_question", "language_comprehension"), 1.0),
    ("SS3", "ss3.english.comprehension.vocab_in_context", "Comprehension", "Vocabulary in context",
     "In 'The minister was lambasted in the press', what does 'lambasted' mean?", "criticised harshly",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.comprehension.vocab_in_context", "Comprehension", "Vocabulary in context",
     "In 'a fleeting glance', what does 'fleeting' mean?", "brief",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.comprehension.tone", "Comprehension", "Tone",
     "What is the tone of: 'Of course, brilliant idea — let us all walk home in the rain.'",
     "sarcastic",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.comprehension.tone", "Comprehension", "Tone",
     "What is the tone of: 'We must rise above this hardship together.'",
     "encouraging",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.comprehension.purpose", "Comprehension", "Author purpose",
     "Why does the author write: 'Buy now — supplies are limited!' ?",
     "to persuade",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.comprehension.purpose", "Comprehension", "Author purpose",
     "Why does the author write: 'Boil the water for five minutes before adding the tea leaves.' ?",
     "to instruct",
     ("language_comprehension",), 0.0),
    ("SS3", "ss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'Of the 480 candidates, only 312 scored above the cut-off.' How many candidates fell below the cut-off?",
     "168",
     ("computation_slip",), 1.0),
    ("SS3", "ss3.english.comprehension.detail", "Comprehension", "Detail",
     "Passage: 'The trip cost ₦24,000 per person; six friends shared the cost equally.' How much did each pay?",
     "4000",
     ("computation_slip",), 0.5),
    ("SS3", "ss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'The streetlights flickered and died.' What can the reader infer?",
     "there was a power cut",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.comprehension.inference", "Comprehension", "Inference",
     "Passage: 'She slid her exam paper under her arm and walked out tall.' What can the reader infer about her result?",
     "she was confident she had done well",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.comprehension.main_idea", "Comprehension", "Title",
     "Best title for: 'Researchers warn that microplastics now appear in human blood, lungs and even unborn babies.'",
     "Microplastics in the Human Body",
     ("language_comprehension", "misread_question"), 1.5),
    ("SS3", "ss3.english.comprehension.main_idea", "Comprehension", "Title",
     "Best title for: 'Solar mini-grids are bringing reliable electricity to towns that NEPA never reached.'",
     "Solar Power for Underserved Towns",
     ("language_comprehension", "misread_question"), 1.5),
    ("SS3", "ss3.english.comprehension.tone", "Comprehension", "Tone",
     "What is the tone of: 'The fragile peace was shattered by a single careless word.'",
     "sombre",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.comprehension.purpose", "Comprehension", "Author purpose",
     "Why does the author write: 'Children should never be left alone near open water.' ?",
     "to warn",
     ("language_comprehension",), 0.5),

    # ---- punctuation & mechanics (71-80) ----
    ("SS3", "ss3.english.mechanics.punctuation", "Mechanics", "Semicolon",
     "Add a semicolon: 'It was raining heavily we still went out.'",
     "It was raining heavily; we still went out.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.mechanics.punctuation", "Mechanics", "Colon",
     "Punctuate with a colon: 'There are three primary colours red blue and yellow.'",
     "There are three primary colours: red, blue and yellow.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.mechanics.punctuation", "Mechanics", "Dash",
     "Add an em-dash: 'Her decision shocked everyone even the judges.'",
     "Her decision shocked everyone—even the judges.",
     ("answer_form",), 1.5),
    ("SS3", "ss3.english.mechanics.punctuation", "Mechanics", "Quotation",
     "Punctuate: 'The chairman said meeting adjourned.'",
     "The chairman said, \"Meeting adjourned.\"",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.mechanics.punctuation", "Mechanics", "Apostrophe",
     "Add an apostrophe: 'The studentss results were posted yesterday.'",
     "The students' results were posted yesterday.",
     ("answer_form",), 0.5),
    ("SS3", "ss3.english.mechanics.capitalisation", "Mechanics", "Capitalisation",
     "Capitalise: 'professor adichie spoke at the university of ibadan last march.'",
     "Professor Adichie spoke at the University of Ibadan last March.",
     ("answer_form",), 0.5),
    ("SS3", "ss3.english.mechanics.spelling", "Mechanics", "Spelling (advanced)",
     "Spell correctly: 'concious'.", "conscious",
     ("transcription", "careless"), 0.5),
    ("SS3", "ss3.english.mechanics.spelling", "Mechanics", "Spelling (advanced)",
     "Spell correctly: 'rythm'.", "rhythm",
     ("transcription", "careless"), 1.0),
    ("SS3", "ss3.english.mechanics.spelling", "Mechanics", "Spelling (advanced)",
     "Spell correctly: 'priviledge'.", "privilege",
     ("transcription", "careless"), 0.5),
    ("SS3", "ss3.english.mechanics.spelling", "Mechanics", "Spelling (advanced)",
     "Spell correctly: 'maintainance'.", "maintenance",
     ("transcription", "careless"), 0.5),

    # ---- sentence transformation & summary (81-90) ----
    ("SS3", "ss3.english.sentence.transformation", "Sentence", "Cleft sentence",
     "Rewrite using 'It was ... that': 'Bola scored the winning goal.'",
     "It was Bola that scored the winning goal.",
     ("answer_form",), 1.5),
    ("SS3", "ss3.english.sentence.transformation", "Sentence", "Inversion",
     "Rewrite using 'Never': 'I have never seen such a crowd.'",
     "Never have I seen such a crowd.",
     ("answer_form",), 1.5),
    ("SS3", "ss3.english.sentence.transformation", "Sentence", "Conditional inversion",
     "Rewrite without 'if': 'If I had known, I would have helped.'",
     "Had I known, I would have helped.",
     ("answer_form",), 2.0),
    ("SS3", "ss3.english.sentence.transformation", "Sentence", "Active/passive",
     "Change to passive: 'Somebody has stolen my bag.'",
     "My bag has been stolen.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.sentence.transformation", "Sentence", "Active/passive",
     "Change to active: 'The book was being read by the student.'",
     "The student was reading the book.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.summary.compress", "Summary", "One-sentence summary",
     "Summarise in one sentence: 'Climate change is altering rainfall patterns across West Africa, with longer dry seasons and shorter but more intense wet seasons that strain farmers and water systems.'",
     "Climate change is making West African rainfall more extreme, hurting farmers and water systems.",
     ("misread_question", "language_comprehension"), 1.5),
    ("SS3", "ss3.english.summary.compress", "Summary", "Topic sentence",
     "Identify the topic sentence: 'Many Nigerian students juggle long commutes, family duties and school. Despite this, performance in WAEC has improved slightly. Teachers credit better revision materials and after-school clubs.'",
     "Despite heavy demands on Nigerian students, WAEC performance has improved.",
     ("misread_question", "language_comprehension"), 1.5),
    ("SS3", "ss3.english.summary.compress", "Summary", "Paraphrase",
     "Paraphrase: 'The judge dismissed the case for lack of evidence.'",
     "The judge threw out the case because there was not enough proof.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.summary.compress", "Summary", "Paraphrase",
     "Paraphrase: 'The bridge has been closed for repairs.'",
     "Workers have shut the bridge so they can fix it.",
     ("answer_form",), 1.0),
    ("SS3", "ss3.english.summary.compress", "Summary", "Concise rewrite",
     "Rewrite more concisely: 'Due to the fact that it was raining, the match was postponed.'",
     "Because it was raining, the match was postponed.",
     ("answer_form",), 0.5),

    # ---- figurative & literary (91-100) ----
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Metaphor",
     "Identify the metaphor: 'Hope is the thing with feathers that perches in the soul.'",
     "hope as a bird",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Personification",
     "Identify the figure of speech: 'The wind whispered through the leaves.'",
     "personification",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Hyperbole",
     "Identify the figure of speech: 'I have told you a million times.'",
     "hyperbole",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Irony",
     "Identify the figure of speech: 'A fire station burned down.'",
     "irony",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Oxymoron",
     "Identify the figure of speech: 'deafening silence'.",
     "oxymoron",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Litotes",
     "Identify the figure of speech: 'Not bad at all.' (meaning very good)",
     "litotes",
     ("language_comprehension",), 2.0),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Idiom",
     "What does 'burn the midnight oil' mean?", "work or study late into the night",
     ("language_comprehension",), 0.5),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Idiom",
     "What does 'a stitch in time saves nine' mean?",
     "act early to prevent more work later",
     ("language_comprehension",), 1.0),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Allusion",
     "In 'He met his Waterloo', what is being alluded to?",
     "a decisive defeat",
     ("language_comprehension",), 1.5),
    ("SS3", "ss3.english.figurative.advanced", "Figurative", "Symbol",
     "In a story, a dove typically symbolises…", "peace",
     ("language_comprehension",), 0.5),
)


def _make_item(idx: int, row: Row) -> dict:
    year, skill, topic, subtopic, prompt, correct, codes, difficulty = row
    item_id = f"english-v1-{year.lower()}-{idx:03d}"
    # Pick item_type heuristically — multi-word or sentence answers are
    # `short_answer`; single-token answers are also `short_answer` (the
    # diagnostic surface treats anything not in a fixed-option set as text).
    return {
        "lang": "en",
        "provenance": [
            {
                "source": "seed-author:pathfinder-learn",
                "source_id": None,
                "rule_id": "w4_english_seed_v1",
                "recency": None,
                "confidence": 1.0,
                "evidence_count": 0,
                "metadata": {
                    "review_state": "pending_two_reviewer_signoff",
                    "subject_lead_approved": False,
                    "safeguarding_reviewed": False,
                },
            }
        ],
        "item_id": item_id,
        "skill_id": skill,
        "prompt": prompt,
        "item_type": "short_answer",
        "difficulty": difficulty,
        "correct_answer": correct,
        "subject": "english",
        "year_group": year,
        "topic": topic,
        "subtopic": subtopic,
        "misconception_codes": list(codes),
        "taxonomy_version": TAXONOMY_VERSION,
    }


def build_bank() -> dict:
    items: List[dict] = []
    for idx, row in enumerate(_JSS3, start=1):
        items.append(_make_item(idx, row))
    for idx, row in enumerate(_SS3, start=1):
        items.append(_make_item(idx, row))

    # Validate every item against the DiagnosticItem contract before write.
    for raw in items:
        DiagnosticItem.model_validate(raw)

    return {
        "bank_id": "english-jss3-ss3-v1",
        "version": "1.0.0",
        "lang": "en",
        "subject": "english",
        "taxonomy_version": TAXONOMY_VERSION,
        "year_groups": ["JSS3", "SS3"],
        "review_state": "pending_two_reviewer_signoff",
        "items": items,
    }


def main() -> int:
    bank = build_bank()
    target = REPO_ROOT / "backend" / "data" / "question_banks" / "english_jss3_ss3_v1.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(bank, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {target} ({len(bank['items'])} items)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
