import { makeStyles } from '@fluentui/react-components'

export const useConversationStyles = makeStyles({
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-md)',
    width: '100%',
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    gap: 'var(--space-xs)',
    padding: 'var(--space-lg)',
    color: 'var(--color-text-tertiary)',
    minHeight: '160px',
  },
  turn: {
    display: 'grid',
    gridTemplateColumns: '32px minmax(0, 1fr)',
    columnGap: 'var(--space-sm)',
    rowGap: '4px',
    alignItems: 'start',
    paddingBlock: 'var(--space-xs)',
    '@media (max-width: 640px)': {
      gridTemplateColumns: '28px minmax(0, 1fr)',
    },
  },
  avatar: {
    gridColumn: '1',
    gridRow: '1 / span 2',
    width: '32px',
    height: '32px',
    borderRadius: '0px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'var(--font-display)',
    fontSize: '0.78rem',
    fontWeight: '700',
    letterSpacing: '0.01em',
    color: 'var(--color-primary-dark)',
    backgroundColor: 'var(--color-primary-soft)',
    border: '1px solid var(--color-border)',
    overflow: 'hidden',
    '@media (max-width: 640px)': {
      width: '28px',
      height: '28px',
      fontSize: '0.72rem',
    },
  },
  avatarChild: {
    backgroundColor: 'rgba(242, 233, 216, 0.8)',
    color: 'var(--color-text-primary)',
  },
  avatarSystem: {
    backgroundColor: 'rgba(255,255,255,0.6)',
    color: 'var(--color-text-tertiary)',
  },
  meta: {
    gridColumn: '2',
    display: 'flex',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    columnGap: 'var(--space-sm)',
    rowGap: '2px',
  },
  actor: {
    fontFamily: 'var(--font-display)',
    fontSize: '0.82rem',
    fontWeight: '700',
    color: 'var(--color-text-primary)',
    letterSpacing: '-0.005em',
  },
  timestamp: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.72rem',
    color: 'var(--color-text-tertiary)',
  },
  body: {
    gridColumn: '2',
    fontFamily: 'var(--font-body)',
    fontSize: '0.9rem',
    lineHeight: 1.55,
    color: 'var(--color-text-primary)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  bodySystem: {
    color: 'var(--color-text-secondary)',
    fontStyle: 'italic',
  },
  inlineContent: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  },
  streamingCursor: {
    display: 'inline-block',
    width: '7px',
    height: '1em',
    verticalAlign: 'text-bottom',
    marginLeft: '2px',
    backgroundColor: 'currentColor',
    opacity: 0.45,
    animationName: {
      '0%': { opacity: 0.2 },
      '50%': { opacity: 0.85 },
      '100%': { opacity: 0.2 },
    },
    animationDuration: '1s',
    animationIterationCount: 'infinite',
  },
  verdictRow: {
    gridColumn: '2',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '2px',
  },
  verdictChip: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '22px',
    paddingInline: '8px',
    borderRadius: '0px',
    fontFamily: 'var(--font-display)',
    fontSize: '0.7rem',
    fontWeight: '600',
    letterSpacing: '0.01em',
    border: '1px solid var(--color-border)',
  },
  verdictCorrect: {
    backgroundColor: 'rgba(13, 138, 132, 0.12)',
    color: 'var(--color-primary-dark)',
  },
  verdictRetry: {
    backgroundColor: 'rgba(242, 233, 216, 0.75)',
    color: 'var(--color-text-primary)',
  },
  verdictOffTarget: {
    backgroundColor: 'rgba(220, 118, 118, 0.12)',
    color: '#8a2f2f',
  },
  phonemeChip: {
    backgroundColor: 'rgba(13, 138, 132, 0.08)',
    color: 'var(--color-primary-dark)',
  },
})
