import { makeStaticStyles } from '@griffel/react'
import { pathfinderTokens, pathfinderTokensDark } from './pathfinder-tokens'

const light = pathfinderTokens
const dark = pathfinderTokensDark

export const usePathfinderThemeStyles = makeStaticStyles({
  '[data-theme]': {
    '--pf-ink': light.brand.ink,
    '--pf-ink-soft': light.brand.inkSoft,
    '--pf-ink-muted': light.brand.inkMuted,
    '--pf-line': light.brand.line,
    '--pf-line-soft': light.brand.lineSoft,
    '--pf-surface': light.brand.surface,
    '--pf-surface-muted': light.brand.surfaceMuted,
    '--pf-page': light.brand.page,
    '--pf-text': light.brand.text,
    '--pf-text-secondary': light.brand.textSecondary,
    '--pf-text-tertiary': light.brand.textTertiary,
    '--pf-on-ink': light.brand.onInk,
    '--pf-hero-bg': light.brand.ink,
    '--pf-hero-fg': light.brand.onInk,
    '--pf-hero-cta-bg': light.brand.onInk,
    '--pf-hero-cta-fg': light.brand.ink,
    '--pf-hero-chip-bg': 'rgba(255,255,255,0.08)',
    '--pf-hero-chip-border': 'rgba(255,255,255,0.16)',
    '--pf-hero-chip-hover-bg': 'rgba(255,255,255,0.13)',
    '--pf-hero-chip-hover-border': 'rgba(255,255,255,0.4)',
    '--pf-hero-focus': 'rgba(255,255,255,0.7)',
    '--pf-status-critical-bg': light.status.criticalBg,
    '--pf-status-critical-fg': light.status.criticalFg,
    '--pf-status-warn-bg': light.status.warnBg,
    '--pf-status-warn-fg': light.status.warnFg,
    '--pf-status-ok-bg': light.status.okBg,
    '--pf-status-ok-fg': light.status.okFg,
    '--pf-status-info-bg': light.status.infoBg,
    '--pf-status-info-fg': light.status.infoFg,
    '--pf-mastery-needs-bg': light.mastery.needsSupportBg,
    '--pf-mastery-needs-fg': light.mastery.needsSupportFg,
    '--pf-mastery-developing-bg': light.mastery.developingBg,
    '--pf-mastery-developing-fg': light.mastery.developingFg,
    '--pf-mastery-approaching-bg': light.mastery.approachingBg,
    '--pf-mastery-approaching-fg': light.mastery.approachingFg,
    '--pf-mastery-secure-bg': light.mastery.secureBg,
    '--pf-mastery-secure-fg': light.mastery.secureFg,
    '--pf-risk-low-bg': light.risk.low.bg,
    '--pf-risk-low-fg': light.risk.low.fg,
    '--pf-risk-review-bg': light.risk.review.bg,
    '--pf-risk-review-fg': light.risk.review.fg,
    '--pf-risk-high-bg': light.risk.high.bg,
    '--pf-risk-high-fg': light.risk.high.fg,
    '--pf-shadow-raised': light.surface.raisedShadow,
    '--pf-shadow-hover': light.surface.hoverShadow,
    '--pf-shadow-card-elevated': light.surface.cardElevatedShadow,
    '--pf-shadow-card-hover': light.surface.cardHoverShadow,
    '--pf-hairline': light.surface.hairline,
    '--pf-space-xxs': light.space.xxs,
    '--pf-space-xs': light.space.xs,
    '--pf-space-sm': light.space.sm,
    '--pf-space-md': light.space.md,
    '--pf-space-lg': light.space.lg,
    '--pf-space-xl': light.space.xl,
    '--pf-space-xxl': light.space.xxl,
    '--pf-space-xxxl': light.space.xxxl,
    '--pf-space-page-x': light.space.pageX,
    '--pf-space-page-y': light.space.pageY,
    '--pf-type-caption-size': light.type.caption.fontSize,
    '--pf-type-caption-line': light.type.caption.lineHeight,
    '--pf-type-body-size': light.type.body.fontSize,
    '--pf-type-body-line': light.type.body.lineHeight,
    '--pf-type-body-strong-size': light.type.bodyStrong.fontSize,
    '--pf-type-body-strong-line': light.type.bodyStrong.lineHeight,
    '--pf-type-title-size': light.type.title.fontSize,
    '--pf-type-title-line': light.type.title.lineHeight,
    '--pf-type-display-size': light.type.display.fontSize,
    '--pf-type-display-line': light.type.display.lineHeight,
    '--pf-focus-ring': light.focus.ring,
    '--pf-focus-ring-soft': light.focus.ringSoft,
    '--pf-focus-outline': light.focus.outline,
    '--pf-motion-fast': light.motion.durationFast,
    '--pf-motion-normal': light.motion.durationNormal,
    '--pf-motion-slow': light.motion.durationSlow,
    '--pf-motion-ease': light.motion.easingStandard,
    '--pf-motion-spring': light.motion.easingSpring,
    '--scrim-bg-tutor':
      'radial-gradient(circle at 50% 18%, #202024 0%, #070708 64%)',
    '--scrim-bg-goal':
      'radial-gradient(circle at 50% 16%, #202024 0%, #070708 64%)',
    '--scrim-bg-onboarding':
      'radial-gradient(circle at 50% 16%, #202024 0%, #070708 64%)',
    '--scrim-bg-voice-agent': 'rgba(10, 10, 10, 0.92)',
    '--scrim-bg-practice':
      'radial-gradient(ellipse at top, #1a1a1d 0%, #050507 70%)',
    '--scrim-fg': '#f7f7f8',
    '--scrim-fg-strong': '#ffffff',
    '--scrim-fg-soft': 'rgba(255,255,255,0.64)',
    '--scrim-fg-muted': 'rgba(255,255,255,0.5)',
    '--scrim-line': 'rgba(255,255,255,0.1)',
    '--scrim-line-soft': 'rgba(255,255,255,0.07)',
    '--scrim-line-strong': 'rgba(255,255,255,0.14)',
    '--scrim-chip': 'rgba(255,255,255,0.06)',
    '--scrim-chip-hover': 'rgba(255,255,255,0.12)',
    '--scrim-card': 'rgba(255,255,255,0.06)',
    '--scrim-card-line': 'rgba(255,255,255,0.08)',
    '--scrim-fill': '#ffffff',
    '--scrim-on-fill': '#0a0a0a',
    '--scrim-ring-color': 'rgba(255,255,255,0.28)',
    '--scrim-brand-dot-glow': '0 0 14px rgba(255,255,255,0.45)',
    '--scrim-orb-bg':
      'radial-gradient(circle at 32% 26%, #ffffff 0%, #d8d8dd 34%, #53535a 68%, #101012 100%)',
    '--scrim-orb-glow':
      '0 0 60px rgba(255,255,255,0.18), inset 0 0 32px rgba(255,255,255,0.2)',
    '--scrim-orb-speaking-glow':
      '0 0 90px rgba(255,255,255,0.34), inset 0 0 32px rgba(255,255,255,0.28)',
    '--scrim-orb-thinking-bg':
      'conic-gradient(from 0deg, #ffffff, #9a9aa2, #ffffff, #54545b, #ffffff)',
    '--scrim-orb-thinking-glow':
      '0 0 76px rgba(255,255,255,0.28), inset 0 0 30px rgba(255,255,255,0.24)',
    '--scrim-wave-color': 'rgba(255,255,255,0.8)',
    '--scrim-vopt-label': '#9bd4ff',
    '--scrim-mic-bg': 'linear-gradient(160deg, #4a4a4d 0%, #090909 100%)',
    '--scrim-mic-shadow': '0 16px 42px rgba(0,0,0,0.42)',
    '--scrim-mic-recording-shadow':
      '0 0 0 8px rgba(255,255,255,0.08), 0 18px 48px rgba(0,0,0,0.5)',
    '--scrim-user-message-bg': '#ffffff',
    '--scrim-user-message-fg': '#0a0a0a',
    '--scrim-assistant-message-bg': 'rgba(255,255,255,0.06)',
    '--scrim-send-bg': '#ffffff',
    '--scrim-send-fg': '#0a0a0a',
  },
  '[data-theme="light"]': {
    '--scrim-bg-tutor':
      'radial-gradient(circle at 50% 14%, #ffffff 0%, #eceef1 72%)',
    '--scrim-bg-goal':
      'radial-gradient(circle at 50% 14%, #ffffff 0%, #eceef1 72%)',
    '--scrim-bg-onboarding':
      'radial-gradient(circle at 50% 14%, #ffffff 0%, #eceef1 72%)',
    '--scrim-bg-voice-agent':
      'radial-gradient(circle at 50% 14%, #ffffff 0%, #eceef1 72%)',
    '--scrim-bg-practice':
      'radial-gradient(circle at 50% 14%, #ffffff 0%, #eceef1 72%)',
    '--scrim-fg': '#0a0a0a',
    '--scrim-fg-strong': '#0a0a0a',
    '--scrim-fg-soft': 'rgba(20,20,22,0.6)',
    '--scrim-fg-muted': 'rgba(20,20,22,0.42)',
    '--scrim-line': '#e5e5ea',
    '--scrim-line-soft': '#e9e9ec',
    '--scrim-line-strong': '#dcdce1',
    '--scrim-chip': '#ffffff',
    '--scrim-chip-hover': '#f2f2f4',
    '--scrim-card': '#ffffff',
    '--scrim-card-line': '#e5e5ea',
    '--scrim-fill': '#0a0a0a',
    '--scrim-on-fill': '#ffffff',
    '--scrim-ring-color': 'rgba(10,10,12,0.16)',
    '--scrim-brand-dot-glow': '0 0 14px rgba(10,10,12,0.2)',
    '--scrim-orb-bg':
      'radial-gradient(circle at 32% 26%, #ffffff 0%, #f1f2f4 38%, #b9bbc2 70%, #565961 100%)',
    '--scrim-orb-glow':
      '0 20px 54px rgba(0,0,0,0.2), inset 0 0 26px rgba(255,255,255,0.55)',
    '--scrim-orb-speaking-glow':
      '0 20px 70px rgba(0,0,0,0.26), inset 0 0 26px rgba(255,255,255,0.62)',
    '--scrim-orb-thinking-bg':
      'conic-gradient(from 0deg, #ffffff, #cfd1d8, #ffffff, #787b84, #ffffff)',
    '--scrim-orb-thinking-glow':
      '0 22px 64px rgba(0,0,0,0.24), inset 0 0 28px rgba(255,255,255,0.6)',
    '--scrim-wave-color': 'rgba(10,10,12,0.62)',
    '--scrim-vopt-label': '#1f5fd0',
    '--scrim-mic-bg': 'linear-gradient(160deg, #2c2c2e 0%, #0a0a0a 100%)',
    '--scrim-mic-shadow': '0 18px 40px rgba(0,0,0,0.22)',
    '--scrim-mic-recording-shadow':
      '0 0 0 8px rgba(10,10,12,0.06), 0 18px 40px rgba(0,0,0,0.22)',
    '--scrim-user-message-bg': '#0a0a0a',
    '--scrim-user-message-fg': '#ffffff',
    '--scrim-assistant-message-bg': '#f2f2f4',
    '--scrim-send-bg': '#0a0a0a',
    '--scrim-send-fg': '#ffffff',
  },
  '[data-theme="dark"]': {
    '--pf-ink': dark.brand.ink,
    '--pf-ink-soft': dark.brand.inkSoft,
    '--pf-ink-muted': dark.brand.inkMuted,
    '--pf-line': dark.brand.line,
    '--pf-line-soft': dark.brand.lineSoft,
    '--pf-surface': dark.brand.surface,
    '--pf-surface-muted': dark.brand.surfaceMuted,
    '--pf-page': dark.brand.page,
    '--pf-text': dark.brand.text,
    '--pf-text-secondary': dark.brand.textSecondary,
    '--pf-text-tertiary': dark.brand.textTertiary,
    '--pf-on-ink': dark.brand.onInk,
    '--pf-hero-bg': '#111113',
    '--pf-hero-fg': dark.brand.text,
    '--pf-hero-cta-bg': dark.brand.ink,
    '--pf-hero-cta-fg': dark.brand.onInk,
    '--pf-hero-chip-bg': 'rgba(255,255,255,0.07)',
    '--pf-hero-chip-border': 'rgba(255,255,255,0.14)',
    '--pf-hero-chip-hover-bg': 'rgba(255,255,255,0.11)',
    '--pf-hero-chip-hover-border': 'rgba(255,255,255,0.32)',
    '--pf-hero-focus': 'rgba(245,245,247,0.72)',
    '--pf-status-critical-bg': dark.status.criticalBg,
    '--pf-status-critical-fg': dark.status.criticalFg,
    '--pf-status-warn-bg': dark.status.warnBg,
    '--pf-status-warn-fg': dark.status.warnFg,
    '--pf-status-ok-bg': dark.status.okBg,
    '--pf-status-ok-fg': dark.status.okFg,
    '--pf-status-info-bg': dark.status.infoBg,
    '--pf-status-info-fg': dark.status.infoFg,
    '--pf-mastery-needs-bg': dark.mastery.needsSupportBg,
    '--pf-mastery-needs-fg': dark.mastery.needsSupportFg,
    '--pf-mastery-developing-bg': dark.mastery.developingBg,
    '--pf-mastery-developing-fg': dark.mastery.developingFg,
    '--pf-mastery-approaching-bg': dark.mastery.approachingBg,
    '--pf-mastery-approaching-fg': dark.mastery.approachingFg,
    '--pf-mastery-secure-bg': dark.mastery.secureBg,
    '--pf-mastery-secure-fg': dark.mastery.secureFg,
    '--pf-risk-low-bg': dark.risk.low.bg,
    '--pf-risk-low-fg': dark.risk.low.fg,
    '--pf-risk-review-bg': dark.risk.review.bg,
    '--pf-risk-review-fg': dark.risk.review.fg,
    '--pf-risk-high-bg': dark.risk.high.bg,
    '--pf-risk-high-fg': dark.risk.high.fg,
    '--pf-shadow-raised': dark.surface.raisedShadow,
    '--pf-shadow-hover': dark.surface.hoverShadow,
    '--pf-shadow-card-elevated': dark.surface.cardElevatedShadow,
    '--pf-shadow-card-hover': dark.surface.cardHoverShadow,
    '--pf-hairline': dark.surface.hairline,
    '--pf-focus-ring': dark.focus.ring,
    '--pf-focus-ring-soft': dark.focus.ringSoft,
    '--pf-focus-outline': dark.focus.outline,
    '--scrim-orb-bg':
      'radial-gradient(circle at 32% 26%, #ffffff 0%, #d8d8dd 34%, #53535a 68%, #101012 100%)',
    '--scrim-orb-glow':
      '0 0 60px rgba(255,255,255,0.18), inset 0 0 32px rgba(255,255,255,0.2)',
    '--scrim-orb-speaking-glow':
      '0 0 90px rgba(255,255,255,0.34), inset 0 0 32px rgba(255,255,255,0.28)',
    '--scrim-orb-thinking-bg':
      'conic-gradient(from 0deg, #ffffff, #9a9aa2, #ffffff, #54545b, #ffffff)',
    '--scrim-orb-thinking-glow':
      '0 0 76px rgba(255,255,255,0.28), inset 0 0 30px rgba(255,255,255,0.24)',
  },
})
