import {
  type Theme,
  webDarkTheme,
  webLightTheme,
} from '@fluentui/react-components'
import {
  pathfinderTokens as t,
  pathfinderTokensDark as td,
} from './pathfinder-tokens'

const inkPressed = '#2c2c2e'
const inkSelected = '#1c1c1e'
const mistPressed = '#d1d1d6'
const darkInkHover = '#ffffff'
const darkInkPressed = '#e4e4e7'
const darkInkSelected = '#f5f5f7'
const darkMistPressed = '#3a3a3c'

export const pathfinderFluentTheme: Theme = {
  ...webLightTheme,
  fontFamilyBase: t.font.text,
  fontFamilyMonospace:
    '"SF Mono", "IBM Plex Mono", "JetBrains Mono", monospace',
  colorNeutralForeground1: t.brand.text,
  colorNeutralForeground2: t.brand.textSecondary,
  colorNeutralForeground3: t.brand.textTertiary,
  colorNeutralForeground4: t.brand.textTertiary,
  colorNeutralForegroundInverted: t.brand.onInk,
  colorBrandForeground1: t.brand.ink,
  colorBrandForeground2: t.brand.inkMuted,
  colorBrandForeground2Hover: t.brand.ink,
  colorBrandForeground2Pressed: inkPressed,
  colorBrandForegroundLink: t.brand.ink,
  colorBrandForegroundLinkHover: t.brand.inkSoft,
  colorBrandForegroundLinkPressed: inkPressed,
  colorBrandForegroundLinkSelected: inkSelected,
  colorCompoundBrandForeground1: t.brand.ink,
  colorCompoundBrandForeground1Hover: t.brand.inkSoft,
  colorCompoundBrandForeground1Pressed: inkPressed,
  colorNeutralForeground3BrandHover: t.brand.ink,
  colorNeutralForeground3BrandPressed: inkPressed,
  colorNeutralForeground3BrandSelected: t.brand.ink,
  colorNeutralBackground1: t.brand.surface,
  colorNeutralBackground1Hover: t.brand.surfaceMuted,
  colorNeutralBackground1Pressed: t.brand.lineSoft,
  colorNeutralBackground1Selected: t.brand.lineSoft,
  colorNeutralBackground2: t.brand.surfaceMuted,
  colorNeutralBackground2Hover: t.brand.lineSoft,
  colorNeutralBackground2Pressed: t.brand.line,
  colorNeutralBackground2Selected: t.brand.line,
  colorNeutralBackground3: t.brand.surface,
  colorNeutralBackground3Hover: t.brand.surfaceMuted,
  colorNeutralBackground3Pressed: t.brand.lineSoft,
  colorNeutralBackground3Selected: t.brand.lineSoft,
  colorSubtleBackground: 'transparent',
  colorSubtleBackgroundHover: t.brand.lineSoft,
  colorSubtleBackgroundPressed: t.brand.line,
  colorSubtleBackgroundSelected: t.brand.lineSoft,
  colorNeutralStroke1: t.brand.line,
  colorNeutralStroke1Hover: t.brand.textTertiary,
  colorNeutralStroke1Pressed: t.brand.textSecondary,
  colorNeutralStroke1Selected: t.brand.textSecondary,
  colorNeutralStroke2: t.brand.lineSoft,
  colorNeutralStrokeAccessible: t.brand.inkMuted,
  colorNeutralStrokeAccessibleHover: t.brand.ink,
  colorNeutralStrokeAccessiblePressed: inkPressed,
  colorNeutralStrokeAccessibleSelected: t.brand.ink,
  colorStrokeFocus1: t.brand.onInk,
  colorStrokeFocus2: t.brand.ink,
  colorBrandBackground: t.brand.ink,
  colorBrandBackgroundHover: t.brand.inkSoft,
  colorBrandBackgroundPressed: inkPressed,
  colorBrandBackgroundSelected: inkSelected,
  colorBrandBackgroundStatic: t.brand.ink,
  colorBrandBackground2: t.brand.lineSoft,
  colorBrandBackground2Hover: t.brand.line,
  colorBrandBackground2Pressed: mistPressed,
  colorBrandBackground3Static: t.brand.inkSoft,
  colorBrandBackground4Static: t.brand.ink,
  colorBrandBackgroundInverted: t.brand.surface,
  colorBrandBackgroundInvertedHover: t.brand.lineSoft,
  colorBrandBackgroundInvertedPressed: t.brand.line,
  colorBrandBackgroundInvertedSelected: t.brand.line,
  colorCompoundBrandBackground: t.brand.ink,
  colorCompoundBrandBackgroundHover: t.brand.inkSoft,
  colorCompoundBrandBackgroundPressed: inkPressed,
  colorBrandStroke1: t.brand.ink,
  colorBrandStroke2: t.brand.line,
  colorBrandStroke2Hover: t.brand.textTertiary,
  colorBrandStroke2Pressed: t.brand.textSecondary,
  colorBrandStroke2Contrast: t.brand.line,
  colorCompoundBrandStroke: t.brand.ink,
  colorCompoundBrandStrokeHover: t.brand.inkSoft,
  colorCompoundBrandStrokePressed: inkPressed,
  colorNeutralStrokeOnBrand: t.brand.onInk,
  colorNeutralStrokeOnBrand2: t.brand.onInk,
  colorNeutralStrokeOnBrand2Hover: t.brand.onInk,
  colorNeutralStrokeOnBrand2Pressed: t.brand.onInk,
  colorNeutralStrokeOnBrand2Selected: t.brand.onInk,
  colorNeutralCardBackground: t.brand.surface,
  colorNeutralCardBackgroundHover: t.brand.surface,
  colorNeutralCardBackgroundPressed: t.brand.surfaceMuted,
  colorNeutralCardBackgroundSelected: t.brand.surfaceMuted,
  colorNeutralShadowAmbient: 'rgba(0, 0, 0, 0.05)',
  colorNeutralShadowKey: 'rgba(0, 0, 0, 0.08)',
  colorBrandShadowAmbient: 'rgba(0, 0, 0, 0.08)',
  colorBrandShadowKey: 'rgba(0, 0, 0, 0.12)',
  colorStatusSuccessBackground1: t.status.okBg,
  colorStatusSuccessForeground1: t.status.okFg,
  colorStatusWarningBackground1: t.status.warnBg,
  colorStatusWarningForeground1: t.status.warnFg,
  colorStatusDangerBackground1: t.status.criticalBg,
  colorStatusDangerForeground1: t.status.criticalFg,
  borderRadiusMedium: t.radius.sm,
  borderRadiusLarge: t.radius.md,
  borderRadiusXLarge: t.radius.lg,
}

export const pathfinderFluentThemeDark: Theme = {
  ...webDarkTheme,
  fontFamilyBase: td.font.text,
  fontFamilyMonospace:
    '"SF Mono", "IBM Plex Mono", "JetBrains Mono", monospace',
  colorNeutralForeground1: td.brand.text,
  colorNeutralForeground2: td.brand.textSecondary,
  colorNeutralForeground3: td.brand.textTertiary,
  colorNeutralForeground4: td.brand.textTertiary,
  colorNeutralForegroundInverted: td.brand.onInk,
  colorBrandForeground1: td.brand.ink,
  colorBrandForeground2: td.brand.inkMuted,
  colorBrandForeground2Hover: darkInkHover,
  colorBrandForeground2Pressed: darkInkPressed,
  colorBrandForegroundLink: td.brand.ink,
  colorBrandForegroundLinkHover: td.brand.inkSoft,
  colorBrandForegroundLinkPressed: darkInkPressed,
  colorBrandForegroundLinkSelected: darkInkSelected,
  colorCompoundBrandForeground1: td.brand.ink,
  colorCompoundBrandForeground1Hover: td.brand.inkSoft,
  colorCompoundBrandForeground1Pressed: darkInkPressed,
  colorNeutralForeground3BrandHover: td.brand.ink,
  colorNeutralForeground3BrandPressed: darkInkPressed,
  colorNeutralForeground3BrandSelected: td.brand.ink,
  colorNeutralBackground1: td.brand.surface,
  colorNeutralBackground1Hover: td.brand.surfaceMuted,
  colorNeutralBackground1Pressed: td.brand.lineSoft,
  colorNeutralBackground1Selected: td.brand.lineSoft,
  colorNeutralBackground2: td.brand.surfaceMuted,
  colorNeutralBackground2Hover: td.brand.lineSoft,
  colorNeutralBackground2Pressed: td.brand.line,
  colorNeutralBackground2Selected: td.brand.line,
  colorNeutralBackground3: td.brand.surface,
  colorNeutralBackground3Hover: td.brand.surfaceMuted,
  colorNeutralBackground3Pressed: td.brand.lineSoft,
  colorNeutralBackground3Selected: td.brand.lineSoft,
  colorSubtleBackground: 'transparent',
  colorSubtleBackgroundHover: td.brand.lineSoft,
  colorSubtleBackgroundPressed: td.brand.line,
  colorSubtleBackgroundSelected: td.brand.lineSoft,
  colorNeutralStroke1: td.brand.line,
  colorNeutralStroke1Hover: td.brand.textTertiary,
  colorNeutralStroke1Pressed: td.brand.textSecondary,
  colorNeutralStroke1Selected: td.brand.textSecondary,
  colorNeutralStroke2: td.brand.lineSoft,
  colorNeutralStrokeAccessible: td.brand.inkMuted,
  colorNeutralStrokeAccessibleHover: td.brand.ink,
  colorNeutralStrokeAccessiblePressed: darkInkPressed,
  colorNeutralStrokeAccessibleSelected: td.brand.ink,
  colorStrokeFocus1: td.brand.onInk,
  colorStrokeFocus2: td.brand.ink,
  colorBrandBackground: td.brand.ink,
  colorBrandBackgroundHover: darkInkHover,
  colorBrandBackgroundPressed: darkInkPressed,
  colorBrandBackgroundSelected: darkInkSelected,
  colorBrandBackgroundStatic: td.brand.ink,
  colorBrandBackground2: td.brand.lineSoft,
  colorBrandBackground2Hover: td.brand.line,
  colorBrandBackground2Pressed: darkMistPressed,
  colorBrandBackground3Static: td.brand.inkSoft,
  colorBrandBackground4Static: td.brand.ink,
  colorBrandBackgroundInverted: td.brand.surface,
  colorBrandBackgroundInvertedHover: td.brand.lineSoft,
  colorBrandBackgroundInvertedPressed: td.brand.line,
  colorBrandBackgroundInvertedSelected: td.brand.line,
  colorCompoundBrandBackground: td.brand.ink,
  colorCompoundBrandBackgroundHover: darkInkHover,
  colorCompoundBrandBackgroundPressed: darkInkPressed,
  colorBrandStroke1: td.brand.ink,
  colorBrandStroke2: td.brand.line,
  colorBrandStroke2Hover: td.brand.textTertiary,
  colorBrandStroke2Pressed: td.brand.textSecondary,
  colorBrandStroke2Contrast: td.brand.line,
  colorCompoundBrandStroke: td.brand.ink,
  colorCompoundBrandStrokeHover: td.brand.inkSoft,
  colorCompoundBrandStrokePressed: darkInkPressed,
  colorNeutralStrokeOnBrand: td.brand.onInk,
  colorNeutralStrokeOnBrand2: td.brand.onInk,
  colorNeutralStrokeOnBrand2Hover: td.brand.onInk,
  colorNeutralStrokeOnBrand2Pressed: td.brand.onInk,
  colorNeutralStrokeOnBrand2Selected: td.brand.onInk,
  colorNeutralCardBackground: td.brand.surface,
  colorNeutralCardBackgroundHover: td.brand.surface,
  colorNeutralCardBackgroundPressed: td.brand.surfaceMuted,
  colorNeutralCardBackgroundSelected: td.brand.surfaceMuted,
  colorNeutralShadowAmbient: 'rgba(0, 0, 0, 0.45)',
  colorNeutralShadowKey: 'rgba(0, 0, 0, 0.6)',
  colorBrandShadowAmbient: 'rgba(0, 0, 0, 0.5)',
  colorBrandShadowKey: 'rgba(0, 0, 0, 0.65)',
  colorStatusSuccessBackground1: td.status.okBg,
  colorStatusSuccessForeground1: td.status.okFg,
  colorStatusWarningBackground1: td.status.warnBg,
  colorStatusWarningForeground1: td.status.warnFg,
  colorStatusDangerBackground1: td.status.criticalBg,
  colorStatusDangerForeground1: td.status.criticalFg,
  borderRadiusMedium: td.radius.sm,
  borderRadiusLarge: td.radius.md,
  borderRadiusXLarge: td.radius.lg,
}
